[package]
name = "entities"
version = "0.1.0"
authors = ["Philip Jackson <p-jackson@live.com>"]
description = "Provides the raw data needed to convert to and from HTML entities."
repository = "https://github.com/p-jackson/entities"
readme = "README.md"
build = "build.rs"
license = "MIT"
keywords = ["HTML", "entities", "character", "escape"]

[build-dependencies]
hyper = "0.9"
json = "0.11"
