name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build; rust-ver=${{ matrix.rust }}
    runs-on: ubuntu-latest

    strategy: 
      fail-fast: false
      matrix:
        rust: [ stable, beta, nightly, "1.13.0", "1.31.0", "1.56.0" ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
      - run: cargo build --release --verbose

  test:
    name: Test; rust-ver=${{ matrix.rust }}
    runs-on: ubuntu-latest

    strategy: 
      fail-fast: false
      matrix:
        rust: [ stable, beta, nightly ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
      - run: cargo test --verbose

  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
